# LubanRDS Docker Default Configuration
# 参考 Redis 配置格式

################################## 网络配置 ##################################

bind 0.0.0.0
port 9736
tcp-backlog 511
timeout 0
tcp-keepalive 300

################################## 通用配置 ##################################

daemonize no
loglevel notice
logfile ""
databases 16

################################## 持久化配置 ##################################

persist-mode rdb
dir /data
dbfilename dump.rdb
rdb-save-interval 60
appendfilename appendonly.aof
appendfsync everysec
aof-fsync-interval 1

################################## 内存管理 ##################################

maxmemory 0
maxmemory-policy noeviction

################################## 安全配置 ##################################

requirepass ""
